1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

The documentation on torch.Tensor. https://pytorch.org/docs/stable/tensors.html#torch-tensor
The documentation on torch.cuda. https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics

2. Create a random tensor with shape (7, 7).


In [2]:
import torch
RANDOM_SEED =  42

In [71]:

torch.manual_seed(RANDOM_SEED)

tensor = torch.rand(7, 7)

In [72]:
tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]])

In [48]:
torch.manual_seed(RANDOM_SEED)

tensor1 = torch.rand(7, 7)

In [51]:
tensor1

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [25]:
tensor3 = torch.rand(1, 7)
print(tensor3)

tensor([[0.6581, 0.4913, 0.8913, 0.1447, 0.5315, 0.1587, 0.6542]])


In [26]:
tensor.shape, tensor3.shape

(torch.Size([7, 7]), torch.Size([1, 7]))

In [27]:
tensor = torch.rand(7, 7)

In [28]:
tensor3.T

tensor([[0.6581],
        [0.4913],
        [0.8913],
        [0.1447],
        [0.5315],
        [0.1587],
        [0.6542]])

In [29]:
tensor_mul = torch.mm(tensor, tensor3.T)


In [30]:
tensor_mul

tensor([[1.2941],
        [1.9662],
        [2.0478],
        [2.0643],
        [1.8984],
        [1.0884],
        [0.9949]])

In [31]:
tensor.size(), tensor3.T.size(), tensor_mul.size()

(torch.Size([7, 7]), torch.Size([7, 1]), torch.Size([7, 1]))

4. Set the random seed to 0 and do 2 & 3 over again.
The output should be:

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))

In [96]:
ms = 0
torch.manual_seed(ms)
t1 =torch.rand(7, 7)

In [97]:

t1

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [98]:
torch.manual_seed(ms)
t2 =torch.rand(1, 7)
t2

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [99]:
t1.shape, t2.shape

(torch.Size([7, 7]), torch.Size([1, 7]))

In [100]:
t1_2 = torch.mm(t1, t2.T)
t1_2

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [101]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)
If there is, set the GPU random seed to 1234.

In [104]:
torch.cuda.manual_seed(123)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [116]:
torch.cuda.manual_seed(123)
# Set random seed
torch.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_1 = torch.rand(size=(2, 3)).to(device)
torch.cuda.manual_seed(123)
# Set random seed
torch.manual_seed(1234)
tensor_2 = torch.rand(size=(2, 3)).to(device)
print(tensor_1, '\n', tensor_2)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) 
 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])


7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
The output should look like:

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))

In [117]:
tensor_1.shape, tensor_2.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [118]:
print(torch.mm(tensor_1, tensor_2.T))

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])


In [119]:
print(torch.matmul(tensor_1, tensor_2.T))

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])


In [121]:
result = torch.matmul(tensor_1, tensor_2.T)

In [122]:
#t8. Find the maximum and minimum values of the output of 7.
torch.min(result) , torch.max(result)

(tensor(0.2161), tensor(0.6287))

In [123]:
#9. Find the maximum and minimum index values of the output of 7.
torch.argmax(result) , torch.argmin(result)

(tensor(3), tensor(2))

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
The output should look like:

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])

In [129]:
torch.manual_seed(7)
random_tensor = torch.rand(size=(1, 1, 1, 10))

In [132]:
random_tensor, random_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [131]:
#To remove a single dimension using squeeze()

squeezed_tensor = random_tensor.squeeze()
squeezed_tensor, squeezed_tensor.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))